In [1]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip -q install optuna

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 8.5 MB/s eta 0:00:00

In [5]:
import optuna
from transformers import set_seed
import numpy as np
import itertools
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
)
from sklearn.metrics import f1_score, accuracy_score

# -----------------------
# A) Load JSONL
# -----------------------
data_files = {
    "train": "/content/drive/MyDrive/nlpPro/data3/HebNLI_train.balanced.jsonl",
    "validation": "/content/drive/MyDrive/nlpPro/data3/HebNLI_val.full.clean.jsonl",
    "test": "/content/drive/MyDrive/nlpPro/data3/HebNLI_test.full.clean.jsonl",
}
ds = load_dataset("json", data_files=data_files)

# -----------------------
# B) Label mapping
# -----------------------
label_list = ["entailment", "contradiction", "neutral"]
label2id = {l: i for i, l in enumerate(label_list)}
id2label = {i: l for l, i in label2id.items()}

def add_label_id(example):
    example["label"] = label2id[str(example["original_label"]).lower()]
    return example

ds = ds.map(add_label_id)

# -----------------------
# C) Tokenizer
# -----------------------
model_name = "avichr/heBERT"
tokenizer = AutoTokenizer.from_pretrained(model_name)

if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({"pad_token": "[PAD]"})

def tokenize_pair(example):
    return tokenizer(
        example["translation1"],
        example["translation2"],
        truncation=True,
        max_length=128,   # <-- keep fixed during tuning (you tested 256 already)
    )

ds_tok = ds.map(tokenize_pair, batched=False)
cols = ["input_ids", "attention_mask", "label"]
ds_tok = ds_tok.remove_columns([c for c in ds_tok["train"].column_names if c not in cols])

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# -----------------------
# D) Metrics
# -----------------------
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "macro_f1": f1_score(labels, preds, average="macro"),
    }

# -----------------------
# E) Model init (fresh model per run)
# -----------------------
def model_init():
    m = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=3,
        id2label=id2label,
        label2id=label2id,
    )
    # if we added pad token, keep embeddings consistent
    if len(tokenizer) != m.config.vocab_size:
        m.resize_token_embeddings(len(tokenizer))
    return m

# -----------------------
# F) GRID SEARCH
# -----------------------
set_seed(42)

def hp_space(trial: optuna.Trial):
    # You can keep the exact same values you had in grid search (categorical),
    # or make some of them continuous (suggest_float(..., log=True)).
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True),
        "weight_decay": trial.suggest_float("weight_decay", 0.0, 0.05),
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [16, 32]),
        "warmup_ratio": trial.suggest_float("warmup_ratio", 0.0, 0.1),
        "num_train_epochs": trial.suggest_categorical("num_train_epochs", [2, 3]),
    }

def compute_objective(metrics):
    # HF will pass eval metrics dict here
    return metrics["eval_macro_f1"]

base_args = TrainingArguments(
    output_dir="hebert_optuna",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    report_to="none",
    seed=42,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
)

trainer = Trainer(
    args=base_args,
    model_init=model_init,  # IMPORTANT: fresh model each trial
    train_dataset=ds_tok["train"],
    eval_dataset=ds_tok["validation"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=1)],
)

best_run = trainer.hyperparameter_search(
    backend="optuna",
    direction="maximize",
    hp_space=hp_space,
    compute_objective=compute_objective,
    n_trials=15,  # change to 30/50 if you can afford it
)

print("Best trial:", best_run)
best_cfg = best_run.hyperparameters
print("BEST CFG:", best_cfg)


# -----------------------
# G) FINAL TRAIN with best hyperparameters (then test ONCE)
# -----------------------
final_args = TrainingArguments(
    output_dir="hebert_final",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    learning_rate=best_cfg["learning_rate"],
    weight_decay=best_cfg["weight_decay"],
    warmup_ratio=best_cfg["warmup_ratio"],
    per_device_train_batch_size=best_cfg["per_device_train_batch_size"],
    per_device_eval_batch_size=32,
    num_train_epochs=best_cfg["num_train_epochs"],
    report_to="none",
    seed=42,
)

final_trainer = Trainer(
    args=final_args,
    model_init=model_init,
    train_dataset=ds_tok["train"],
    eval_dataset=ds_tok["validation"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

final_trainer.train()

print("\nTEST:")
test_metrics = final_trainer.evaluate(ds_tok["test"])
print(test_metrics)

Map:   0%|          | 0/11823 [00:00<?, ? examples/s]

Map:   0%|          | 0/1999 [00:00<?, ? examples/s]

Map:   0%|          | 0/884 [00:00<?, ? examples/s]

Map:   0%|          | 0/11823 [00:00<?, ? examples/s]

Map:   0%|          | 0/1999 [00:00<?, ? examples/s]

Map:   0%|          | 0/884 [00:00<?, ? examples/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[I 2026-01-21 06:48:50,973] A new study created in memory with name: no-name-333502b1-91f3-480d-8557-1eac6616007d

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:50:14,205] Trial 0 finished with value: 0.632502297460102 and parameters: {'learning_rate': 3.8203754352945106e-05, 'weight_decay': 0.0482831621666357, 'per_device_train_batch_size': 32, 'warmup_ratio': 0.011538169260700826, 'num_train_epochs': 2}. Best is trial 0 with value: 0.632502297460102.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:51:35,197] Trial 1 finished with value: 0.636809327416628 and parameters: {'learning_rate': 4.275999814909803e-05, 'weight_decay': 0.0228005401170649, 'per_device_train_batch_size': 32, 'warmup_ratio': 0.04905498758930763, 'num_train_epochs': 2}. Best is trial 1 with value: 0.636809327416628.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:52:56,200] Trial 2 finished with value: 0.6242128995783282 and parameters: {'learning_rate': 2.543309984987318e-05, 'weight_decay': 0.04692240864005451, 'per_device_train_batch_size': 32, 'warmup_ratio': 0.017487356362407402, 'num_train_epochs': 2}. Best is trial 1 with value: 0.636809327416628.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:54:22,930] Trial 3 finished with value: 0.6391948427027129 and parameters: {'learning_rate': 3.23654591745491e-05, 'weight_decay': 0.03896128167005955, 'per_device_train_batch_size': 16, 'warmup_ratio': 0.08906164399134997, 'num_train_epochs': 2}. Best is trial 3 with value: 0.6391948427027129.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:56:32,096] Trial 4 finished with value: 0.6347931523640278 and parameters: {'learning_rate': 3.918689184729243e-05, 'weight_decay': 0.008789257099121572, 'per_device_train_batch_size': 16, 'warmup_ratio': 0.018753191059949204, 'num_train_epochs': 3}. Best is trial 3 with value: 0.6391948427027129.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:57:11,320] Trial 5 pruned.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:57:53,511] Trial 6 pruned.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:58:32,788] Trial 7 pruned.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:59:14,966] Trial 8 pruned.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 06:59:57,125] Trial 9 pruned.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 07:00:39,321] Trial 10 pruned.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 07:02:00,193] Trial 11 finished with value: 0.6382468688421391 and parameters: {'learning_rate': 4.961408757756963e-05, 'weight_decay': 0.0022835841856826515, 'per_device_train_batch_size': 32, 'warmup_ratio': 0.05823875591675785, 'num_train_epochs': 2}. Best is trial 3 with value: 0.6391948427027129.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 07:02:39,311] Trial 12 pruned.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 07:03:21,298] Trial 13 pruned.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2026-01-21 07:05:21,921] Trial 14 finished with value: 0.6316236946775414 and parameters: {'learning_rate': 4.597203841638522e-05, 'weight_decay': 0.011306944188803647, 'per_device_train_batch_size': 32, 'warmup_ratio': 0.06045497180709688, 'num_train_epochs': 3}. Best is trial 3 with value: 0.6391948427027129.

Best trial: BestRun(run_id='3', objective=0.6391948427027129, hyperparameters={'learning_rate': 3.23654591745491e-05, 'weight_decay': 0.03896128167005955, 'per_device_train_batch_size': 16, 'warmup_ratio': 0.08906164399134997, 'num_train_epochs': 2}, run_summary=None)
BEST CFG: {'learning_rate': 3.23654591745491e-05, 'weight_decay': 0.03896128167005955, 'per_device_train_batch_size': 16, 'warmup_ratio': 0.08906164399134997, 'num_train_epochs': 2}

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at avichr/heBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

TEST:

{'eval_loss': 0.8208246231079102, 'eval_accuracy': 0.665158371040724, 'eval_macro_f1': 0.6640215726429824, 'eval_runtime': 0.9117, 'eval_samples_per_second': 969.626, 'eval_steps_per_second': 30.712, 'epoch': 2.0}